clients/urls.py
from django.urls import path
from . import views


app_name = "clients"
urlpatterns = [
    path("", views.ClientListView.as_view(), name="index"),
    path("<int:pk>/cliente/", views.ClientDetailView.as_view(), name="client"),
    path("<int:pk>/cliente/edicao/", views.ClientUpdateView.as_view(), name="change"),
    path("novo/", views.ClientCreateView.as_view(), name="add"),
    path("<int:pk>/cliente/remocao/", views.ClientDeleteView.as_view(), name="delete"),
]

core/urls.py
from django.urls import path
from . import views


app_name = "core"
urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
]

setup/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("clientes/", include("clients.urls")),
]

clients/models.py
from django.db import models


class Client(models.Model):
    GENDER = [
        ("F", "Feminino"),
        ("M", "Masculino"),
        (
            "N",
            "Não binário",
        ),
    ]
    STATUS = [
        ("G", "Em dia"),
        ("Y", "Mensal"),
        ("R", "Devedor"),
    ]
    name = models.CharField("nome", max_length=128)
    birth_date = models.DateField("data de nascimento")
    gender = models.CharField("gênero", max_length=1, choices=GENDER)
    address = models.CharField("endereço", max_length=128, null=True)
    email = models.EmailField(max_length=32, null=True)
    phone = models.CharField(max_length=16, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_purchase_date = models.DateField("data da última compra", null=True)
    status = models.CharField(max_length=1, choices=STATUS, null=True)
    occurrences = models.TextField("ocorrências", max_length=1024, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "cliente"

core/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models

# Create your models here.

clients/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView, ListView
from .models import Client


class ClientCreateView(CreateView):
    model = Client
    fields = [
        "name",
        "birth_date",
        "gender",
        "address",
        "email",
        "phone",
        "occurrences",
    ]
    success_url = reverse_lazy("clients:index")


class ClientDetailView(DetailView):
    model = Client


class ClientListView(ListView):
    model = Client


class ClientUpdateView(UpdateView):
    model = Client
    fields = [
        "name",
        "birth_date",
        "gender",
        "address",
        "email",
        "phone",
        "last_purchase_date",
        "status",
        "occurrences",
    ]
    success_url = reverse_lazy("clients:index")


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy("clients:index")

core/views.py
from django.views.generic.base import TemplateView


class HomePageView(TemplateView):
    template_name = "core/home.html"

products/views.py
from django.shortcuts import render

# Create your views here.

clients/templates/clients/client_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block links %}
  <link rel="stylesheet" href="{% static 'css/forms.css' %}" />
{% endblock %}
{% block header %}
  <h1>Tem certeza?</h1>
{% endblock %}
{% block content %}
  <p>Você tem certeza que quer remover o cliente "{{ context }}"?</p>
  <form method="post" style="height: 800px;">
    {% csrf_token %}
    {{ form }}
    <div>
      <input class="btn btn-danger" type="submit" value="Sim, eu tenho certeza" />
      <a class="btn btn-warning" href="{% url 'clients:index' %}">Não, me leve de volta</a>
    </div>
  </form>
{% endblock %}

clients/templates/clients/client_detail.html
<p>Nome: {{ object.name }}</p>
<p>Data de nascimento: {{ object.birth_date }}</p>
<p>Gênero: {{ object.gender }}</p>
<p>Endereço: {{ object.address }}</p>
<p>Telefone: {{ object.phone }}</p>
<p>Data de cadastro: {{ object.created_at }}</p>
<p>Data da última compra: {{ object.last_purchase_date }}</p>
<p>Status: {{ object.status }}</p>
<hr>

clients/templates/clients/client_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block links %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}
{% block header %}
  <h1>Editando cliente</h1>
{% endblock %}
{% block content %}
  <form class="form-container" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div>
      <input class="btn btn-save" type="submit" value="Salvar" />
      <a class="btn btn-warning" href="{% url 'clients:index' %}">Cancelar</a>
    </div>
  </form>
{% endblock %}

clients/templates/clients/client_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block links %}
  <link rel="stylesheet" href="{% static 'css/tables.css' %}" />
{% endblock %}
{% block header %}
  <h1>Clientes</h1>
{% endblock %}
{% block content %}
  <div style="margin-top: 15px;">
    <a class="btn btn-default" href="{% url 'clients:add' %}">Novo cliente</a>
  </div>
  <div style="margin-top: 15px;">
    <table>
      <tr>
        <th>Nome</th>
        <th>Endereço</th>
        <th>Email</th>
        <th>Telefone</th>
        <th>Data da última compra</th>
        <th>Status</th>
        <th>Ação</th>
      </tr>
      {% for client in object_list %}
        <tr>
          <td>{{ client.name }}</td>
          <td>{{ client.address }}</td>
          <td>{{ client.email }}</td>
          <td>{{ client.phone }}</td>
          <td>{{ client.last_purchase_date }}</td>
          <td>{{ client.status }}</td>
          <td>
            <a href="{% url 'clients:client' client.pk %}">Detalhe</a>
            <a href="{% url 'clients:delete' client.pk %}">Excluir</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}" />
    {% block links %}

    {% endblock %}
    <title>
      {% block title %}
        Home
      {% endblock %}
    </title>
  </head>
  <body>
    <div>
      <section class="header">
        {% block header %}

        {% endblock %}
      </section>
      <section class="sidenav">
        <a id="home" href="{% url 'core:home' %}">Home</a>
        <a id="clients" href="{% url 'clients:index' %}">Clientes</a>
        <a id="products" href="#" id="products">Produtos</a>
        <a id="sales" href="#" id="sales">Vendas</a>
        <a id="suppliers" href="#" id="suppliers">Fornecedores</a>
      </section>
      <section class="content">
        <div style="padding-left: 200px; padding-right: 20px;">
          {% block content %}
          {% endblock %}
        </div>
      </section>
      <section class="footer">
        <p>Desenvolvido por: israelbrito&#169;</p>
        <p>israelcvb21@gmail.com</p>
        <p>2024</p>
      </section>
    </div>
  </body>
</html>